CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
  ID               UUID NOT NULL,
  COMPLETION_DATE  TIMESTAMP,
  EVENT_TYPE       VARCHAR(512) NOT NULL,
  LISTENER_ID      VARCHAR(512) NOT NULL,
  PUBLICATION_DATE TIMESTAMP NOT NULL,
  SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
  COMPLETION_ATTEMPTS INTEGER,
  LAST_RESUBMISSION_DATE TIMESTAMP,
  STATUS           VARCHAR(20),
  PRIMARY KEY (ID)
);
